name: chat_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  fpdart: ^1.2.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
